require:
  - rubocop-rspec
  - rubocop-rails

Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false

Rails/FilePath:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
